spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.96.14.71:3306/robot?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 336699yst.
  application:
    name: accessdata
  output:
    ansi:
      enabled: always
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763