spring:
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 39.96.14.71:9300
  application:
    name: matchword
  output:
    ansi:
      enabled: always
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762

